-- MySQL Script generated by MySQL Workbench
-- Sat Jun 27 13:27:04 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quanlysua
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `quanlysua` ;

-- -----------------------------------------------------
-- Schema quanlysua
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quanlysua` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `quanlysua` ;

-- -----------------------------------------------------
-- Table `quanlysua`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quanlysua`.`role` ;

CREATE TABLE IF NOT EXISTS `quanlysua`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `uq_role_name` (`role_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysua`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quanlysua`.`user` ;

CREATE TABLE IF NOT EXISTS `quanlysua`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) NULL DEFAULT NULL,
  `google_id` VARCHAR(50) NULL DEFAULT NULL,
  `avatar_url` VARCHAR(500) NULL DEFAULT NULL,
  `role_id` INT NOT NULL,
  `is_deleted` TINYINT(1) NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `uq_user_email` (`email` ASC) VISIBLE,
  INDEX `idx_google_id` (`google_id` ASC) VISIBLE,
  INDEX `fk_users_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `quanlysua`.`role` (`role_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysua`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quanlysua`.`cart` ;

CREATE TABLE IF NOT EXISTS `quanlysua`.`cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cart_id`),
  UNIQUE INDEX `uq_cart_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `quanlysua`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysua`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quanlysua`.`category` ;

CREATE TABLE IF NOT EXISTS `quanlysua`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `uq_category_name` (`category_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysua`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quanlysua`.`product` ;

CREATE TABLE IF NOT EXISTS `quanlysua`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `category_id` INT NOT NULL,
  `price` DECIMAL(12,2) NOT NULL,
  `quantity` INT NOT NULL,
  `discount_percent` INT NULL DEFAULT '0',
  `image_url` VARCHAR(500) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NULL DEFAULT '0',
  `is_hot` TINYINT(1) NULL DEFAULT '0',
  `expiration_date` DATE NOT NULL,
  PRIMARY KEY (`product_id`, `expiration_date`),
  INDEX `fk_product_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `quanlysua`.`category` (`category_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysua`.`cart_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quanlysua`.`cart_item` ;

CREATE TABLE IF NOT EXISTS `quanlysua`.`cart_item` (
  `cart_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL DEFAULT '1',
  `is_checked` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`cart_id`, `product_id`),
  INDEX `fk_cart_item_product` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_item_cart`
    FOREIGN KEY (`cart_id`)
    REFERENCES `quanlysua`.`cart` (`cart_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_cart_item_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `quanlysua`.`product` (`product_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysua`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quanlysua`.`orders` ;

CREATE TABLE IF NOT EXISTS `quanlysua`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `status` ENUM('pending', 'processing', 'shipping', 'delivered', 'cancelled') NULL DEFAULT 'pending',
  `full_name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `delivery_address` VARCHAR(255) NOT NULL,
  `order_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `delivery_date` DATETIME NULL DEFAULT NULL,
  `shipping_fee` DECIMAL(12,2) NULL DEFAULT '0.00',
  `total_amount` DECIMAL(12,2) NOT NULL,
  `is_paid` TINYINT(1) NULL DEFAULT '0',
  `payment_method` ENUM('COD', 'MOMO', 'VNPAY', 'BANK_TRANSFER') NULL DEFAULT 'COD',
  `note` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `quanlysua`.`user` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysua`.`order_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quanlysua`.`order_detail` ;

CREATE TABLE IF NOT EXISTS `quanlysua`.`order_detail` (
  `order_detail_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(150) NOT NULL,
  `price` DECIMAL(12,2) NOT NULL,
  `quantity` INT NOT NULL,
  `total_item_amount` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`order_detail_id`),
  INDEX `fk_order_detail_orders_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_detail_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_detail_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `quanlysua`.`orders` (`order_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_order_detail_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `quanlysua`.`product` (`product_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysua`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quanlysua`.`payments` ;

CREATE TABLE IF NOT EXISTS `quanlysua`.`payments` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `payment_method` VARCHAR(50) NOT NULL,
  `transaction_code` VARCHAR(100) NULL DEFAULT NULL,
  `bank_code` VARCHAR(50) NULL DEFAULT NULL,
  `response_code` VARCHAR(10) NULL DEFAULT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `status` ENUM('PENDING', 'SUCCESS', 'FAILED') NULL DEFAULT 'PENDING',
  `payment_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `note` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_payments_orders_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_payments_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `quanlysua`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysua`.`product_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quanlysua`.`product_detail` ;

CREATE TABLE IF NOT EXISTS `quanlysua`.`product_detail` (
  `product_id` INT NOT NULL,
  `origin` VARCHAR(255) NULL DEFAULT NULL,
  `ingredients` TEXT NULL DEFAULT NULL,
  `usage` TEXT NULL DEFAULT NULL,
  `storage` TEXT NULL DEFAULT NULL,
  `calories` DECIMAL(5,2) NULL DEFAULT '0.00',
  `protein` DECIMAL(5,2) NULL DEFAULT '0.00',
  `fat` DECIMAL(5,2) NULL DEFAULT '0.00',
  `carbohydrates` DECIMAL(5,2) NULL DEFAULT '0.00',
  `sugar` DECIMAL(5,2) NULL DEFAULT '0.00',
  `vitamins` JSON NULL DEFAULT NULL,
  `minerals` JSON NULL DEFAULT NULL,
  `other_nutrients` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `fk_product_detail_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `quanlysua`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;